### ISSUE TITLE
Error: Traceback (most recent call last):   File "instagram_har.py", line 91, in <module>     json.loads(req['response']['content']['text'])['data']['user']) KeyError: 'user'

### ISSUE THREAD

**Issue by illiniguy23** [metamemelord/Instagram-har-downloader#1]
When not logged in, I can extract and download images from HAR files successfully using Instagram-har-downloader. 

In order to view more images, I logged in to Instagram, reloaded the page, scrolled to the bottom, and downloaded the HAR file again. However, I received this error when running Instagram-har-downloader on the HAR file containing all posts:

```
Traceback (most recent call last):
  File "instagram_har.py", line 91, in <module>
    json.loads(req['response']['content']['text'])['data']['user'])
KeyError: 'user'

```

**Comment by illiniguy23** [comment]
I was having trouble replicating this issue, so I'm going to close it. Please feel free to delete this issue.
